sonar.projectKey=pxti-web-app
sonar.projectName=pxti-web-app
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**, src/**/*.module.ts, src/**/*.js, src/**/main.ts, src/**/test.ts, src/environments/**, src/**/*.config.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.test.exclusions=**/node_modules/**, src/**/*.module.ts, src/**/*.js, src/**/main.ts, src/**/test.ts, src/environments/**, src/**/*.config.ts
sonar.javascript.lcov.reportPaths=coverage/pxti-web-app/lcov.info
sonar.testExecutionReportPaths=test-report.xml
sonar.typescript.node=/node/node
